# Generated by Django 5.2.17 on 2026-09-19 14:49

import django.core.validators
import django.db.models.deletion
from decimal import Decimal
from django.db import migrations, models


class Migration(migrations.Migration):

    initial = True

    dependencies = [
        ('factories', '0002_productionline_code'),
        ('production', '0005_finishedgooddispatch_and_reconciliation_results'),
    ]

    operations = [
        migrations.CreateModel(
            name='Customer',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('code', models.CharField(max_length=50)),
                ('name', models.CharField(max_length=150)),
                ('contact_name', models.CharField(blank=True, max_length=150)),
                ('email', models.EmailField(blank=True, max_length=254)),
                ('phone', models.CharField(blank=True, max_length=50)),
                ('is_active', models.BooleanField(default=True)),
                ('created_at', models.DateTimeField(auto_now_add=True)),
                ('updated_at', models.DateTimeField(auto_now=True)),
                ('factory', models.ForeignKey(on_delete=django.db.models.deletion.PROTECT, related_name='customers', to='factories.factory')),
            ],
            options={
                'verbose_name': 'Customer',
                'verbose_name_plural': 'Customers',
                'ordering': ('factory', 'name'),
            },
        ),
        migrations.CreateModel(
            name='CustomerOrder',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('reference', models.CharField(max_length=50)),
                ('order_date', models.DateField()),
                ('status', models.CharField(choices=[('OPEN', 'Open'), ('PARTIALLY_ALLOCATED', 'Partially allocated'), ('ALLOCATED', 'Allocated'), ('CANCELLED', 'Cancelled')], default='OPEN', max_length=20)),
                ('notes', models.TextField(blank=True)),
                ('created_at', models.DateTimeField(auto_now_add=True)),
                ('updated_at', models.DateTimeField(auto_now=True)),
                ('customer', models.ForeignKey(on_delete=django.db.models.deletion.PROTECT, related_name='orders', to='orders.customer')),
                ('factory', models.ForeignKey(on_delete=django.db.models.deletion.PROTECT, related_name='customer_orders', to='factories.factory')),
            ],
            options={
                'verbose_name': 'Customer Order',
                'verbose_name_plural': 'Customer Orders',
                'ordering': ('-order_date', 'factory', 'reference'),
            },
        ),
        migrations.CreateModel(
            name='CustomerOrderLine',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('quantity', models.DecimalField(decimal_places=3, help_text='Ordered quantity. Must be greater than zero.', max_digits=12, validators=[django.core.validators.MinValueValidator(Decimal('0.001'))])),
                ('created_at', models.DateTimeField(auto_now_add=True)),
                ('updated_at', models.DateTimeField(auto_now=True)),
                ('customer_order', models.ForeignKey(on_delete=django.db.models.deletion.PROTECT, related_name='lines', to='orders.customerorder')),
                ('finished_good', models.ForeignKey(on_delete=django.db.models.deletion.PROTECT, related_name='order_lines', to='production.finishedgood')),
            ],
            options={
                'verbose_name': 'Customer Order Line',
                'verbose_name_plural': 'Customer Order Lines',
                'ordering': ('customer_order', 'id'),
            },
        ),
        migrations.CreateModel(
            name='DispatchAllocation',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('quantity', models.DecimalField(decimal_places=3, help_text='Allocated quantity. Must be greater than zero.', max_digits=12, validators=[django.core.validators.MinValueValidator(Decimal('0.001'))])),
                ('created_at', models.DateTimeField(auto_now_add=True)),
                ('updated_at', models.DateTimeField(auto_now=True)),
                ('dispatch', models.ForeignKey(on_delete=django.db.models.deletion.PROTECT, related_name='allocations', to='production.finishedgooddispatch')),
                ('order_line', models.ForeignKey(on_delete=django.db.models.deletion.PROTECT, related_name='allocations', to='orders.customerorderline')),
            ],
            options={
                'verbose_name': 'Dispatch Allocation',
                'verbose_name_plural': 'Dispatch Allocations',
                'ordering': ('-created_at', 'order_line'),
            },
        ),
        migrations.AddConstraint(
            model_name='customer',
            constraint=models.UniqueConstraint(fields=('factory', 'code'), name='unique_customer_code_per_factory'),
        ),
        migrations.AddConstraint(
            model_name='customerorder',
            constraint=models.UniqueConstraint(fields=('factory', 'reference'), name='unique_customer_order_reference_per_factory'),
        ),
        migrations.AddConstraint(
            model_name='customerorderline',
            constraint=models.CheckConstraint(condition=models.Q(('quantity__gt', 0)), name='customer_order_line_quantity_greater_than_zero'),
        ),
        migrations.AddConstraint(
            model_name='dispatchallocation',
            constraint=models.CheckConstraint(condition=models.Q(('quantity__gt', 0)), name='dispatch_allocation_quantity_greater_than_zero'),
        ),
    ]
