# Generated by Django 5.2.17 on 2026-09-19 14:57

import django.core.validators
import django.db.models.deletion
from decimal import Decimal
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('orders', '0001_initial'),
        ('production', '0005_finishedgooddispatch_and_reconciliation_results'),
    ]

    operations = [
        migrations.AddField(
            model_name='customerorder',
            name='fulfilment_status',
            field=models.CharField(choices=[('UNFULFILLED', 'Unfulfilled'), ('PARTIALLY_FULFILLED', 'Partially fulfilled'), ('FULFILLED', 'Fulfilled')], default='UNFULFILLED', help_text='Derived from dispatch allocations. Does not replace commercial status.', max_length=30),
        ),
        migrations.CreateModel(
            name='OrderReservation',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('quantity', models.DecimalField(decimal_places=3, help_text='Committed quantity. Must be greater than zero. Does not reduce inventory.', max_digits=12, validators=[django.core.validators.MinValueValidator(Decimal('0.001'))])),
                ('created_at', models.DateTimeField(auto_now_add=True)),
                ('updated_at', models.DateTimeField(auto_now=True)),
                ('order_line', models.ForeignKey(on_delete=django.db.models.deletion.PROTECT, related_name='reservations', to='orders.customerorderline')),
                ('warehouse', models.ForeignKey(on_delete=django.db.models.deletion.PROTECT, related_name='reservations', to='production.warehouse')),
            ],
            options={
                'verbose_name': 'Order Reservation',
                'verbose_name_plural': 'Order Reservations',
                'ordering': ('-created_at', 'order_line'),
                'constraints': [models.CheckConstraint(condition=models.Q(('quantity__gt', 0)), name='order_reservation_quantity_greater_than_zero')],
            },
        ),
    ]
