# Generated by Django 5.2.17 on 2026-09-19 13:23

import django.core.validators
import django.db.models.deletion
import django.utils.timezone
from decimal import Decimal
from django.db import migrations, models


class Migration(migrations.Migration):

    initial = True

    dependencies = [
        ('factories', '0002_productionline_code'),
    ]

    operations = [
        migrations.CreateModel(
            name='ProductionRun',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('reference', models.CharField(max_length=50)),
                ('status', models.CharField(choices=[('PLANNED', 'Planned'), ('IN_PROGRESS', 'In progress'), ('COMPLETED', 'Completed'), ('CANCELLED', 'Cancelled')], default='PLANNED', max_length=20)),
                ('started_at', models.DateTimeField(blank=True, null=True)),
                ('ended_at', models.DateTimeField(blank=True, null=True)),
                ('notes', models.TextField(blank=True)),
                ('created_at', models.DateTimeField(auto_now_add=True)),
                ('updated_at', models.DateTimeField(auto_now=True)),
                ('factory', models.ForeignKey(on_delete=django.db.models.deletion.PROTECT, related_name='production_runs', to='factories.factory')),
            ],
            options={
                'verbose_name': 'Production Run',
                'verbose_name_plural': 'Production Runs',
                'ordering': ('-created_at', 'factory', 'reference'),
            },
        ),
        migrations.CreateModel(
            name='ProductionOutput',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('output_name', models.CharField(max_length=150)),
                ('quantity', models.DecimalField(decimal_places=3, help_text='Quantity produced. Must be greater than zero.', max_digits=12, validators=[django.core.validators.MinValueValidator(Decimal('0.001'))])),
                ('recorded_at', models.DateTimeField(default=django.utils.timezone.now, help_text='When this output was recorded.')),
                ('created_at', models.DateTimeField(auto_now_add=True)),
                ('updated_at', models.DateTimeField(auto_now=True)),
                ('production_run', models.ForeignKey(on_delete=django.db.models.deletion.PROTECT, related_name='outputs', to='production.productionrun')),
            ],
            options={
                'verbose_name': 'Production Output',
                'verbose_name_plural': 'Production Outputs',
                'ordering': ('-recorded_at', 'production_run'),
            },
        ),
        migrations.AddConstraint(
            model_name='productionrun',
            constraint=models.UniqueConstraint(fields=('factory', 'reference'), name='unique_production_run_reference_per_factory'),
        ),
        migrations.AddConstraint(
            model_name='productionrun',
            constraint=models.CheckConstraint(condition=models.Q(('ended_at__isnull', True), models.Q(('started_at__isnull', False), ('ended_at__gte', models.F('started_at'))), _connector='OR'), name='production_run_ended_at_not_before_started_at'),
        ),
        migrations.AddConstraint(
            model_name='productionoutput',
            constraint=models.CheckConstraint(condition=models.Q(('quantity__gt', 0)), name='production_output_quantity_greater_than_zero'),
        ),
    ]
