# Generated by Django 5.2.17 on 2026-09-19 13:41

import django.core.validators
import django.db.models.deletion
import django.utils.timezone
from decimal import Decimal
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('production', '0001_initial'),
    ]

    operations = [
        migrations.CreateModel(
            name='ProductionReject',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('quantity', models.DecimalField(decimal_places=3, help_text='Quantity of production output rejected. Must be greater than zero.', max_digits=12, validators=[django.core.validators.MinValueValidator(Decimal('0.001'))])),
                ('occurred_at', models.DateTimeField(default=django.utils.timezone.now, help_text='When this reject occurred.')),
                ('reason', models.CharField(max_length=200)),
                ('created_at', models.DateTimeField(auto_now_add=True)),
                ('updated_at', models.DateTimeField(auto_now=True)),
                ('production_run', models.ForeignKey(on_delete=django.db.models.deletion.PROTECT, related_name='rejects', to='production.productionrun')),
            ],
            options={
                'verbose_name': 'Production Reject',
                'verbose_name_plural': 'Production Rejects',
                'ordering': ('-occurred_at', 'production_run'),
                'constraints': [models.CheckConstraint(condition=models.Q(('quantity__gt', 0)), name='production_reject_quantity_greater_than_zero')],
            },
        ),
    ]
