# Generated by Django 5.2.17 on 2026-09-19 14:12

import django.db.models.deletion
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('factories', '0002_productionline_code'),
        ('production', '0002_productionreject'),
    ]

    operations = [
        migrations.AlterField(
            model_name='productionoutput',
            name='output_name',
            field=models.CharField(blank=True, max_length=150),
        ),
        migrations.CreateModel(
            name='FinishedGood',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('code', models.CharField(max_length=50)),
                ('name', models.CharField(max_length=150)),
                ('description', models.TextField(blank=True)),
                ('is_active', models.BooleanField(default=True)),
                ('created_at', models.DateTimeField(auto_now_add=True)),
                ('updated_at', models.DateTimeField(auto_now=True)),
                ('factory', models.ForeignKey(on_delete=django.db.models.deletion.PROTECT, related_name='finished_goods', to='factories.factory')),
            ],
            options={
                'verbose_name': 'Finished Good',
                'verbose_name_plural': 'Finished Goods',
                'ordering': ('factory', 'name'),
            },
        ),
        migrations.AddField(
            model_name='productionoutput',
            name='finished_good',
            field=models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.PROTECT, related_name='outputs', to='production.finishedgood'),
        ),
        migrations.AddConstraint(
            model_name='finishedgood',
            constraint=models.UniqueConstraint(fields=('factory', 'code'), name='unique_finished_good_code_per_factory'),
        ),
    ]
