# Generated by Django 5.2.17 on 2026-09-19 14:27

import django.core.validators
import django.db.models.deletion
import django.utils.timezone
from decimal import Decimal
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('factories', '0002_productionline_code'),
        ('production', '0003_alter_productionoutput_output_name_finishedgood_and_more'),
    ]

    operations = [
        migrations.CreateModel(
            name='Warehouse',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('code', models.CharField(max_length=50)),
                ('name', models.CharField(max_length=150)),
                ('description', models.TextField(blank=True)),
                ('is_active', models.BooleanField(default=True)),
                ('created_at', models.DateTimeField(auto_now_add=True)),
                ('updated_at', models.DateTimeField(auto_now=True)),
                ('factory', models.ForeignKey(on_delete=django.db.models.deletion.PROTECT, related_name='warehouses', to='factories.factory')),
            ],
            options={
                'verbose_name': 'Warehouse',
                'verbose_name_plural': 'Warehouses',
                'ordering': ('factory', 'name'),
            },
        ),
        migrations.CreateModel(
            name='FinishedGoodStockRecord',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('recording_date', models.DateField()),
                ('opening_quantity', models.DecimalField(decimal_places=3, help_text='Counted quantity at the start of the recording date.', max_digits=12, validators=[django.core.validators.MinValueValidator(Decimal('0'))])),
                ('closing_quantity', models.DecimalField(blank=True, decimal_places=3, help_text='Counted quantity at the end of the recording date. Leave blank if closing has not been recorded yet.', max_digits=12, null=True, validators=[django.core.validators.MinValueValidator(Decimal('0'))])),
                ('created_at', models.DateTimeField(auto_now_add=True)),
                ('updated_at', models.DateTimeField(auto_now=True)),
                ('finished_good', models.ForeignKey(on_delete=django.db.models.deletion.PROTECT, related_name='stock_records', to='production.finishedgood')),
                ('warehouse', models.ForeignKey(on_delete=django.db.models.deletion.PROTECT, related_name='stock_records', to='production.warehouse')),
            ],
            options={
                'verbose_name': 'Finished Good Stock Record',
                'verbose_name_plural': 'Finished Good Stock Records',
                'ordering': ('-recording_date', 'warehouse', 'finished_good'),
            },
        ),
        migrations.CreateModel(
            name='FinishedGoodReconciliation',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('reconciliation_date', models.DateField()),
                ('notes', models.TextField(blank=True)),
                ('created_at', models.DateTimeField(auto_now_add=True)),
                ('updated_at', models.DateTimeField(auto_now=True)),
                ('finished_good', models.ForeignKey(on_delete=django.db.models.deletion.PROTECT, related_name='reconciliations', to='production.finishedgood')),
                ('warehouse', models.ForeignKey(on_delete=django.db.models.deletion.PROTECT, related_name='reconciliations', to='production.warehouse')),
            ],
            options={
                'verbose_name': 'Finished Good Reconciliation',
                'verbose_name_plural': 'Finished Good Reconciliations',
                'ordering': ('-reconciliation_date', 'warehouse', 'finished_good'),
            },
        ),
        migrations.CreateModel(
            name='FinishedGoodAdjustment',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('quantity', models.DecimalField(decimal_places=3, help_text='Absolute quantity to increase or decrease. Must be greater than zero.', max_digits=12, validators=[django.core.validators.MinValueValidator(Decimal('0.001'))])),
                ('adjustment_type', models.CharField(choices=[('INCREASE', 'Increase'), ('DECREASE', 'Decrease')], max_length=20)),
                ('occurred_at', models.DateTimeField(default=django.utils.timezone.now, help_text='When this adjustment occurred.')),
                ('reason', models.CharField(max_length=200)),
                ('created_at', models.DateTimeField(auto_now_add=True)),
                ('updated_at', models.DateTimeField(auto_now=True)),
                ('finished_good', models.ForeignKey(on_delete=django.db.models.deletion.PROTECT, related_name='adjustments', to='production.finishedgood')),
                ('warehouse', models.ForeignKey(on_delete=django.db.models.deletion.PROTECT, related_name='adjustments', to='production.warehouse')),
            ],
            options={
                'verbose_name': 'Finished Good Adjustment',
                'verbose_name_plural': 'Finished Good Adjustments',
                'ordering': ('-occurred_at', 'warehouse', 'finished_good'),
            },
        ),
        migrations.CreateModel(
            name='FinishedGoodAddition',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('quantity', models.DecimalField(decimal_places=3, help_text='Quantity of finished goods received. Must be greater than zero.', max_digits=12, validators=[django.core.validators.MinValueValidator(Decimal('0.001'))])),
                ('added_at', models.DateTimeField(default=django.utils.timezone.now, help_text='When these finished goods entered inventory.')),
                ('created_at', models.DateTimeField(auto_now_add=True)),
                ('updated_at', models.DateTimeField(auto_now=True)),
                ('finished_good', models.ForeignKey(on_delete=django.db.models.deletion.PROTECT, related_name='additions', to='production.finishedgood')),
                ('production_output', models.ForeignKey(blank=True, help_text='Optional production output this addition came from.', null=True, on_delete=django.db.models.deletion.PROTECT, related_name='stock_additions', to='production.productionoutput')),
                ('warehouse', models.ForeignKey(on_delete=django.db.models.deletion.PROTECT, related_name='additions', to='production.warehouse')),
            ],
            options={
                'verbose_name': 'Finished Good Addition',
                'verbose_name_plural': 'Finished Good Additions',
                'ordering': ('-added_at', 'warehouse', 'finished_good'),
            },
        ),
        migrations.AddConstraint(
            model_name='warehouse',
            constraint=models.UniqueConstraint(fields=('factory', 'code'), name='unique_warehouse_code_per_factory'),
        ),
        migrations.AddConstraint(
            model_name='finishedgoodstockrecord',
            constraint=models.UniqueConstraint(fields=('warehouse', 'finished_good', 'recording_date'), name='unique_fg_stock_record_per_warehouse_item_date'),
        ),
        migrations.AddConstraint(
            model_name='finishedgoodstockrecord',
            constraint=models.CheckConstraint(condition=models.Q(('opening_quantity__gte', 0)), name='fg_stock_record_opening_quantity_non_negative'),
        ),
        migrations.AddConstraint(
            model_name='finishedgoodstockrecord',
            constraint=models.CheckConstraint(condition=models.Q(('closing_quantity__gte', 0), ('closing_quantity__isnull', True), _connector='OR'), name='fg_stock_record_closing_quantity_non_negative'),
        ),
        migrations.AddConstraint(
            model_name='finishedgoodreconciliation',
            constraint=models.UniqueConstraint(fields=('warehouse', 'finished_good', 'reconciliation_date'), name='unique_fg_reconciliation_per_warehouse_item_date'),
        ),
        migrations.AddConstraint(
            model_name='finishedgoodadjustment',
            constraint=models.CheckConstraint(condition=models.Q(('quantity__gt', 0)), name='fg_adjustment_quantity_greater_than_zero'),
        ),
        migrations.AddConstraint(
            model_name='finishedgoodaddition',
            constraint=models.CheckConstraint(condition=models.Q(('quantity__gt', 0)), name='fg_addition_quantity_greater_than_zero'),
        ),
    ]
