# Generated by Django 5.2.17 on 2026-09-20 15:30

import django.db.models.deletion
from django.conf import settings
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('factories', '0002_productionline_code'),
        ('machines', '0002_machine_status'),
        ('production', '0005_finishedgooddispatch_and_reconciliation_results'),
        migrations.swappable_dependency(settings.AUTH_USER_MODEL),
    ]

    operations = [
        migrations.AddField(
            model_name='productionrun',
            name='created_by',
            field=models.ForeignKey(
                blank=True,
                help_text='Operator who started the run. Set server-side.',
                null=True,
                on_delete=django.db.models.deletion.SET_NULL,
                related_name='production_runs',
                to=settings.AUTH_USER_MODEL,
            ),
        ),
        migrations.AddField(
            model_name='productionrun',
            name='production_line',
            field=models.ForeignKey(
                blank=True,
                help_text='Line this run was started on. Required for operator-started runs.',
                null=True,
                on_delete=django.db.models.deletion.PROTECT,
                related_name='production_runs',
                to='factories.productionline',
            ),
        ),
        migrations.AddField(
            model_name='productionrun',
            name='machine',
            field=models.ForeignKey(
                blank=True,
                help_text='Machine this run was started on. Required for operator-started runs.',
                null=True,
                on_delete=django.db.models.deletion.PROTECT,
                related_name='production_runs',
                to='machines.machine',
            ),
        ),
    ]
