# Generated by Django 5.2.17 on 2026-09-20 18:00

import django.core.validators
import django.db.models.deletion
import django.utils.timezone
from decimal import Decimal
from django.conf import settings
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('materials', '0008_materialconsumption_batch_recorded_by'),
        ('production', '0006_productionrun_line_machine_operator'),
        migrations.swappable_dependency(settings.AUTH_USER_MODEL),
    ]

    operations = [
        migrations.CreateModel(
            name='ProductionRunMaterialState',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('roll_quantity', models.DecimalField(
                    decimal_places=3,
                    help_text='Quantity currently loaded on the machine. May be zero.',
                    max_digits=12,
                    validators=[django.core.validators.MinValueValidator(Decimal('0'))],
                )),
                ('spare_roll_quantity', models.DecimalField(
                    decimal_places=3,
                    help_text='Spare quantity available beside the machine. May be zero.',
                    max_digits=12,
                    validators=[django.core.validators.MinValueValidator(Decimal('0'))],
                )),
                ('recorded_at', models.DateTimeField(
                    default=django.utils.timezone.now,
                    help_text='When this machine material state was recorded.',
                )),
                ('created_at', models.DateTimeField(auto_now_add=True)),
                ('updated_at', models.DateTimeField(auto_now=True)),
                ('material', models.ForeignKey(
                    on_delete=django.db.models.deletion.PROTECT,
                    related_name='run_material_states',
                    to='materials.material',
                )),
                ('production_run', models.ForeignKey(
                    on_delete=django.db.models.deletion.PROTECT,
                    related_name='material_states',
                    to='production.productionrun',
                )),
                ('recorded_by', models.ForeignKey(
                    blank=True,
                    help_text='User who recorded this snapshot. Set server-side.',
                    null=True,
                    on_delete=django.db.models.deletion.SET_NULL,
                    related_name='production_run_material_states',
                    to=settings.AUTH_USER_MODEL,
                )),
            ],
            options={
                'verbose_name': 'Production Run Material State',
                'verbose_name_plural': 'Production Run Material States',
                'ordering': ('-recorded_at', 'production_run', 'material'),
                'constraints': [
                    models.CheckConstraint(
                        condition=models.Q(roll_quantity__gte=0),
                        name='production_run_material_state_roll_quantity_not_negative',
                    ),
                    models.CheckConstraint(
                        condition=models.Q(spare_roll_quantity__gte=0),
                        name='production_run_material_state_spare_quantity_not_negative',
                    ),
                ],
            },
        ),
    ]
