# Generated by Django 6.1.1 on 2026-10-10 00:09

import apps.production.models
import django.core.validators
import django.db.models.deletion
import django.utils.timezone
from decimal import Decimal
from django.conf import settings
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('catalog', '0001_initial_catalog'),
        ('factories', '0002_productionline_code'),
        ('production', '0007_productionrunmaterialstate'),
        migrations.swappable_dependency(settings.AUTH_USER_MODEL),
    ]

    operations = [
        migrations.AddField(
            model_name='productionrun',
            name='packaging',
            field=models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.PROTECT, related_name='production_runs', to='catalog.packaging'),
        ),
        migrations.AddField(
            model_name='productionrun',
            name='planned_pack_quantity',
            field=models.DecimalField(blank=True, decimal_places=3, help_text='How many packs are planned, for example 20 in 20 × 15s.', max_digits=12, null=True, validators=[django.core.validators.MinValueValidator(Decimal('0.001'))]),
        ),
        migrations.AddField(
            model_name='productionrun',
            name='product',
            field=models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.PROTECT, related_name='production_runs', to='catalog.product'),
        ),
        migrations.AddField(
            model_name='productionrun',
            name='stage',
            field=models.CharField(blank=True, choices=[('DRAFT', 'Draft'), ('INPUTS_COMPLETE', 'Inputs complete'), ('PRODUCTION_ACTIVE', 'Production active'), ('OUTPUT_RECORDED', 'Output recorded'), ('QC_REQUIRED', 'QC required'), ('QC_COMPLETE', 'QC complete'), ('VALIDATION', 'Validation'), ('COMPLETED', 'Completed'), ('EXCEPTION', 'Exception'), ('CANCELLED', 'Cancelled')], help_text='V1.1 production-control stage. Empty on legacy runs.', max_length=30, null=True),
        ),
        migrations.AddField(
            model_name='productionrun',
            name='variant',
            field=models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.PROTECT, related_name='production_runs', to='catalog.productvariant'),
        ),
        migrations.CreateModel(
            name='FactoryProductionPolicy',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('tolerance_pct', models.DecimalField(decimal_places=3, default=Decimal('0'), help_text='Absolute percentage variance allowed before a run becomes an exception.', max_digits=7, validators=[django.core.validators.MinValueValidator(Decimal('0'))])),
                ('min_qc_photos', models.PositiveSmallIntegerField(default=1, help_text='Photos required before QC can complete a run.')),
                ('created_at', models.DateTimeField(auto_now_add=True)),
                ('updated_at', models.DateTimeField(auto_now=True)),
                ('factory', models.OneToOneField(on_delete=django.db.models.deletion.PROTECT, related_name='production_policy', to='factories.factory')),
            ],
            options={
                'verbose_name': 'Factory Production Policy',
                'verbose_name_plural': 'Factory Production Policies',
            },
        ),
        migrations.CreateModel(
            name='QCVerification',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('expected_quantity', models.DecimalField(blank=True, decimal_places=3, help_text='Computed individual units. Stored at validation time.', max_digits=12, null=True, validators=[django.core.validators.MinValueValidator(Decimal('0'))])),
                ('recorded_quantity', models.DecimalField(blank=True, decimal_places=3, help_text='Operator recorded individual units. Preserved, not overwritten by QC.', max_digits=12, null=True, validators=[django.core.validators.MinValueValidator(Decimal('0'))])),
                ('qc_verified_quantity', models.DecimalField(blank=True, decimal_places=3, help_text='Quantity QC physically confirmed, in individual units.', max_digits=12, null=True, validators=[django.core.validators.MinValueValidator(Decimal('0'))])),
                ('status', models.CharField(choices=[('PENDING', 'Pending'), ('VERIFIED', 'Verified'), ('EXCEPTION', 'Exception')], default='PENDING', max_length=20)),
                ('verified_at', models.DateTimeField(blank=True, null=True)),
                ('created_at', models.DateTimeField(auto_now_add=True)),
                ('updated_at', models.DateTimeField(auto_now=True)),
                ('packaging', models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.PROTECT, related_name='qc_verifications', to='catalog.packaging')),
                ('production_run', models.OneToOneField(on_delete=django.db.models.deletion.PROTECT, related_name='qc_verification', to='production.productionrun')),
                ('variant', models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.PROTECT, related_name='qc_verifications', to='catalog.productvariant')),
                ('verified_by', models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.SET_NULL, related_name='qc_verifications', to=settings.AUTH_USER_MODEL)),
            ],
            options={
                'verbose_name': 'QC Verification',
                'verbose_name_plural': 'QC Verifications',
            },
        ),
        migrations.CreateModel(
            name='QCPhoto',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('image', models.FileField(upload_to=apps.production.models.qc_photo_upload_to)),
                ('caption', models.CharField(blank=True, max_length=200)),
                ('uploaded_at', models.DateTimeField(default=django.utils.timezone.now)),
                ('created_at', models.DateTimeField(auto_now_add=True)),
                ('updated_at', models.DateTimeField(auto_now=True)),
                ('uploaded_by', models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.SET_NULL, related_name='qc_photos', to=settings.AUTH_USER_MODEL)),
                ('qc_verification', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='photos', to='production.qcverification')),
            ],
            options={
                'verbose_name': 'QC Photo',
                'verbose_name_plural': 'QC Photos',
                'ordering': ('-uploaded_at',),
            },
        ),
    ]
