# Generated by Django 6.1.1 on 2026-10-10 14:53

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('accounts', '0002_alter_user_managers'),
        ('machines', '0002_machine_status'),
    ]

    operations = [
        migrations.AddField(
            model_name='user',
            name='assigned_machines',
            field=models.ManyToManyField(blank=True, help_text='Printing-station operators may set up and run only these machines. Leave empty for every other role.', related_name='assigned_users', to='machines.machine'),
        ),
    ]
