# Generated by Django 5.2.17 on 2026-09-19 12:34

import django.core.validators
import django.db.models.deletion
from decimal import Decimal
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('factories', '0002_productionline_code'),
        ('materials', '0001_initial'),
    ]

    operations = [
        migrations.CreateModel(
            name='StockRecord',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('recording_date', models.DateField()),
                ('opening_quantity', models.DecimalField(decimal_places=3, help_text='Counted quantity at the start of the recording date.', max_digits=12, validators=[django.core.validators.MinValueValidator(Decimal('0'))])),
                ('closing_quantity', models.DecimalField(blank=True, decimal_places=3, help_text='Counted quantity at the end of the recording date. Leave blank if closing has not been recorded yet.', max_digits=12, null=True, validators=[django.core.validators.MinValueValidator(Decimal('0'))])),
                ('created_at', models.DateTimeField(auto_now_add=True)),
                ('updated_at', models.DateTimeField(auto_now=True)),
                ('factory', models.ForeignKey(on_delete=django.db.models.deletion.PROTECT, related_name='stock_records', to='factories.factory')),
                ('material', models.ForeignKey(on_delete=django.db.models.deletion.PROTECT, related_name='stock_records', to='materials.material')),
            ],
            options={
                'verbose_name': 'Stock Record',
                'verbose_name_plural': 'Stock Records',
                'ordering': ('-recording_date', 'factory', 'material'),
                'constraints': [models.UniqueConstraint(fields=('factory', 'material', 'recording_date'), name='unique_stock_record_per_factory_material_date'), models.CheckConstraint(condition=models.Q(('opening_quantity__gte', 0)), name='stock_record_opening_quantity_non_negative'), models.CheckConstraint(condition=models.Q(('closing_quantity__gte', 0), ('closing_quantity__isnull', True), _connector='OR'), name='stock_record_closing_quantity_non_negative')],
            },
        ),
    ]
