# Generated by Django 5.2.17 on 2026-09-19 13:03

import django.core.validators
import django.db.models.deletion
import django.utils.timezone
from decimal import Decimal
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('factories', '0002_productionline_code'),
        ('materials', '0002_stockrecord'),
    ]

    operations = [
        migrations.CreateModel(
            name='MaterialBatch',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('lot_number', models.CharField(max_length=100)),
                ('created_at', models.DateTimeField(auto_now_add=True)),
                ('updated_at', models.DateTimeField(auto_now=True)),
                ('material', models.ForeignKey(on_delete=django.db.models.deletion.PROTECT, related_name='batches', to='materials.material')),
            ],
            options={
                'verbose_name': 'Material Batch',
                'verbose_name_plural': 'Material Batches',
                'ordering': ('material', 'lot_number'),
            },
        ),
        migrations.CreateModel(
            name='MaterialAddition',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('quantity', models.DecimalField(decimal_places=3, help_text='Quantity of material received. Must be greater than zero.', max_digits=12, validators=[django.core.validators.MinValueValidator(Decimal('0.001'))])),
                ('added_at', models.DateTimeField(default=django.utils.timezone.now, help_text='When this material physically entered the factory.')),
                ('created_at', models.DateTimeField(auto_now_add=True)),
                ('updated_at', models.DateTimeField(auto_now=True)),
                ('factory', models.ForeignKey(on_delete=django.db.models.deletion.PROTECT, related_name='material_additions', to='factories.factory')),
                ('material', models.ForeignKey(on_delete=django.db.models.deletion.PROTECT, related_name='additions', to='materials.material')),
                ('batch', models.ForeignKey(on_delete=django.db.models.deletion.PROTECT, related_name='additions', to='materials.materialbatch')),
            ],
            options={
                'verbose_name': 'Material Addition',
                'verbose_name_plural': 'Material Additions',
                'ordering': ('-added_at', 'factory', 'material'),
            },
        ),
        migrations.AddConstraint(
            model_name='materialbatch',
            constraint=models.UniqueConstraint(fields=('material', 'lot_number'), name='unique_lot_number_per_material'),
        ),
        migrations.AddConstraint(
            model_name='materialaddition',
            constraint=models.CheckConstraint(condition=models.Q(('quantity__gt', 0)), name='material_addition_quantity_greater_than_zero'),
        ),
    ]
