# Generated by Django 5.2.17 on 2026-09-19 13:14

import django.core.validators
import django.db.models.deletion
import django.utils.timezone
from decimal import Decimal
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('factories', '0002_productionline_code'),
        ('materials', '0003_materialbatch_materialaddition_and_more'),
    ]

    operations = [
        migrations.CreateModel(
            name='MaterialConsumption',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('quantity', models.DecimalField(decimal_places=3, help_text='Quantity of material consumed. Must be greater than zero.', max_digits=12, validators=[django.core.validators.MinValueValidator(Decimal('0.001'))])),
                ('consumed_at', models.DateTimeField(default=django.utils.timezone.now, help_text='When this material was physically used.')),
                ('production_reference', models.CharField(blank=True, help_text='Optional production activity reference. Not a production-run link.', max_length=100)),
                ('created_at', models.DateTimeField(auto_now_add=True)),
                ('updated_at', models.DateTimeField(auto_now=True)),
                ('factory', models.ForeignKey(on_delete=django.db.models.deletion.PROTECT, related_name='material_consumptions', to='factories.factory')),
                ('material', models.ForeignKey(on_delete=django.db.models.deletion.PROTECT, related_name='consumptions', to='materials.material')),
            ],
            options={
                'verbose_name': 'Material Consumption',
                'verbose_name_plural': 'Material Consumptions',
                'ordering': ('-consumed_at', 'factory', 'material'),
                'constraints': [models.CheckConstraint(condition=models.Q(('quantity__gt', 0)), name='material_consumption_quantity_greater_than_zero')],
            },
        ),
    ]
