# Generated by Django 5.2.17 on 2026-09-19 13:41

import django.core.validators
import django.db.models.deletion
import django.utils.timezone
from decimal import Decimal
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('factories', '0002_productionline_code'),
        ('materials', '0004_materialconsumption'),
    ]

    operations = [
        migrations.CreateModel(
            name='MaterialScrap',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('quantity', models.DecimalField(decimal_places=3, help_text='Quantity of material scrapped. Must be greater than zero.', max_digits=12, validators=[django.core.validators.MinValueValidator(Decimal('0.001'))])),
                ('occurred_at', models.DateTimeField(default=django.utils.timezone.now, help_text='When this scrap occurred.')),
                ('reason', models.CharField(max_length=200)),
                ('created_at', models.DateTimeField(auto_now_add=True)),
                ('updated_at', models.DateTimeField(auto_now=True)),
                ('factory', models.ForeignKey(on_delete=django.db.models.deletion.PROTECT, related_name='material_scraps', to='factories.factory')),
                ('material', models.ForeignKey(on_delete=django.db.models.deletion.PROTECT, related_name='scraps', to='materials.material')),
            ],
            options={
                'verbose_name': 'Material Scrap',
                'verbose_name_plural': 'Material Scrap',
                'ordering': ('-occurred_at', 'factory', 'material'),
                'constraints': [models.CheckConstraint(condition=models.Q(('quantity__gt', 0)), name='material_scrap_quantity_greater_than_zero')],
            },
        ),
        migrations.CreateModel(
            name='MaterialWaste',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('quantity', models.DecimalField(decimal_places=3, help_text='Quantity of material lost as waste. Must be greater than zero.', max_digits=12, validators=[django.core.validators.MinValueValidator(Decimal('0.001'))])),
                ('occurred_at', models.DateTimeField(default=django.utils.timezone.now, help_text='When this waste occurred.')),
                ('reason', models.CharField(max_length=200)),
                ('created_at', models.DateTimeField(auto_now_add=True)),
                ('updated_at', models.DateTimeField(auto_now=True)),
                ('factory', models.ForeignKey(on_delete=django.db.models.deletion.PROTECT, related_name='material_wastes', to='factories.factory')),
                ('material', models.ForeignKey(on_delete=django.db.models.deletion.PROTECT, related_name='wastes', to='materials.material')),
            ],
            options={
                'verbose_name': 'Material Waste',
                'verbose_name_plural': 'Material Waste',
                'ordering': ('-occurred_at', 'factory', 'material'),
                'constraints': [models.CheckConstraint(condition=models.Q(('quantity__gt', 0)), name='material_waste_quantity_greater_than_zero')],
            },
        ),
        migrations.CreateModel(
            name='StockReconciliation',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('reconciliation_date', models.DateField()),
                ('notes', models.TextField(blank=True)),
                ('created_at', models.DateTimeField(auto_now_add=True)),
                ('updated_at', models.DateTimeField(auto_now=True)),
                ('factory', models.ForeignKey(on_delete=django.db.models.deletion.PROTECT, related_name='stock_reconciliations', to='factories.factory')),
                ('material', models.ForeignKey(on_delete=django.db.models.deletion.PROTECT, related_name='stock_reconciliations', to='materials.material')),
            ],
            options={
                'verbose_name': 'Stock Reconciliation',
                'verbose_name_plural': 'Stock Reconciliations',
                'ordering': ('-reconciliation_date', 'factory', 'material'),
                'constraints': [models.UniqueConstraint(fields=('factory', 'material', 'reconciliation_date'), name='unique_stock_reconciliation_per_factory_material_date')],
            },
        ),
    ]
