# Generated by Django 5.2.17 on 2026-09-19 14:06

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('materials', '0005_materialscrap_materialwaste_stockreconciliation'),
    ]

    operations = [
        migrations.AddField(
            model_name='stockreconciliation',
            name='actual_closing_quantity',
            field=models.DecimalField(blank=True, decimal_places=3, help_text='Copied from the matching stock record closing quantity.', max_digits=12, null=True),
        ),
        migrations.AddField(
            model_name='stockreconciliation',
            name='calculated_at',
            field=models.DateTimeField(blank=True, null=True),
        ),
        migrations.AddField(
            model_name='stockreconciliation',
            name='expected_closing_quantity',
            field=models.DecimalField(blank=True, decimal_places=3, help_text='Opening + additions − consumption − waste − scrap.', max_digits=12, null=True),
        ),
        migrations.AddField(
            model_name='stockreconciliation',
            name='variance_quantity',
            field=models.DecimalField(blank=True, decimal_places=3, help_text='Actual closing minus expected closing. Positive means more stock than expected.', max_digits=12, null=True),
        ),
    ]
