# Generated by Django 5.2.17 on 2026-09-19 14:12

import django.db.models.deletion
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('materials', '0006_stockreconciliation_actual_closing_quantity_and_more'),
        ('production', '0002_productionreject'),
    ]

    operations = [
        migrations.AddField(
            model_name='materialconsumption',
            name='production_run',
            field=models.ForeignKey(blank=True, help_text='Optional production run this consumption belongs to.', null=True, on_delete=django.db.models.deletion.PROTECT, related_name='material_consumptions', to='production.productionrun'),
        ),
        migrations.AlterField(
            model_name='materialconsumption',
            name='production_reference',
            field=models.CharField(blank=True, help_text='Optional free-text production activity reference. Prefer production_run for traceability.', max_length=100),
        ),
    ]
