# Generated by Django 5.2.17 on 2026-09-20 16:00

import django.db.models.deletion
from django.conf import settings
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('materials', '0007_materialconsumption_production_run_and_more'),
        migrations.swappable_dependency(settings.AUTH_USER_MODEL),
    ]

    operations = [
        migrations.AddField(
            model_name='materialconsumption',
            name='batch',
            field=models.ForeignKey(
                blank=True,
                help_text='Lot consumed. Required for operator-recorded consumption.',
                null=True,
                on_delete=django.db.models.deletion.PROTECT,
                related_name='consumptions',
                to='materials.materialbatch',
            ),
        ),
        migrations.AddField(
            model_name='materialconsumption',
            name='recorded_by',
            field=models.ForeignKey(
                blank=True,
                help_text='User who recorded the consumption. Set server-side.',
                null=True,
                on_delete=django.db.models.deletion.SET_NULL,
                related_name='material_consumptions',
                to=settings.AUTH_USER_MODEL,
            ),
        ),
    ]
