# Generated by Django 6.1.1 on 2026-09-15 17:50

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('machines', '0001_initial'),
    ]

    operations = [
        migrations.AddField(
            model_name='machine',
            name='status',
            field=models.CharField(choices=[('operational', 'Operational'), ('maintenance', 'In Maintenance'), ('offline', 'Offline'), ('decommissioned', 'Decommissioned')], default='offline', max_length=20),
        ),
    ]
