# Generated by Django 6.1.1 on 2026-09-15 17:50

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('factories', '0001_initial'),
    ]

    operations = [
        migrations.AddField(
            model_name='productionline',
            name='code',
            field=models.CharField(blank=True, max_length=50),
        ),
    ]
