# Generated by Django 6.1.1 on 2026-10-10 00:10

import django.db.models.deletion
from django.conf import settings
from django.db import migrations, models


class Migration(migrations.Migration):

    initial = True

    dependencies = [
        ('contenttypes', '0002_remove_content_type_name'),
        ('factories', '0002_productionline_code'),
        migrations.swappable_dependency(settings.AUTH_USER_MODEL),
    ]

    operations = [
        migrations.CreateModel(
            name='AuditEvent',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('action', models.CharField(choices=[('STAGE_CHANGE', 'Stage change'), ('QC_VERIFIED', 'QC verified'), ('CORRECTION', 'Correction'), ('EXCEPTION_ACCEPTED', 'Exception accepted')], max_length=50)),
                ('target_object_id', models.PositiveBigIntegerField()),
                ('field_name', models.CharField(blank=True, max_length=100)),
                ('old_value', models.TextField(blank=True)),
                ('new_value', models.TextField(blank=True)),
                ('reason', models.TextField(blank=True)),
                ('created_at', models.DateTimeField(auto_now_add=True)),
                ('actor', models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.SET_NULL, related_name='audit_events', to=settings.AUTH_USER_MODEL)),
                ('factory', models.ForeignKey(on_delete=django.db.models.deletion.PROTECT, related_name='audit_events', to='factories.factory')),
                ('target_content_type', models.ForeignKey(on_delete=django.db.models.deletion.PROTECT, to='contenttypes.contenttype')),
            ],
            options={
                'verbose_name': 'Audit Event',
                'verbose_name_plural': 'Audit Events',
                'ordering': ('-created_at',),
                'indexes': [models.Index(fields=['factory', 'created_at'], name='audit_audit_factory_31c9df_idx'), models.Index(fields=['target_content_type', 'target_object_id'], name='audit_audit_target__1e9cda_idx')],
            },
        ),
    ]
