# Generated by Django 6.1.1 on 2026-10-10 00:09

import django.core.validators
import django.db.models.deletion
from decimal import Decimal
from django.db import migrations, models


class Migration(migrations.Migration):

    initial = True

    dependencies = [
        ('factories', '0002_productionline_code'),
        ('production', '0007_productionrunmaterialstate'),
    ]

    operations = [
        migrations.CreateModel(
            name='Product',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('code', models.CharField(max_length=50)),
                ('name', models.CharField(max_length=150)),
                ('is_active', models.BooleanField(default=True)),
                ('created_at', models.DateTimeField(auto_now_add=True)),
                ('updated_at', models.DateTimeField(auto_now=True)),
                ('factory', models.ForeignKey(on_delete=django.db.models.deletion.PROTECT, related_name='products', to='factories.factory')),
            ],
            options={
                'verbose_name': 'Product',
                'verbose_name_plural': 'Products',
                'ordering': ('factory', 'name'),
            },
        ),
        migrations.CreateModel(
            name='ProductVariant',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('code', models.CharField(max_length=50)),
                ('name', models.CharField(max_length=100)),
                ('is_active', models.BooleanField(default=True)),
                ('created_at', models.DateTimeField(auto_now_add=True)),
                ('updated_at', models.DateTimeField(auto_now=True)),
                ('finished_good', models.ForeignKey(blank=True, help_text='Optional link into the finished-goods warehouse chain.', null=True, on_delete=django.db.models.deletion.PROTECT, related_name='product_variants', to='production.finishedgood')),
                ('product', models.ForeignKey(on_delete=django.db.models.deletion.PROTECT, related_name='variants', to='catalog.product')),
            ],
            options={
                'verbose_name': 'Product Variant',
                'verbose_name_plural': 'Product Variants',
                'ordering': ('product', 'name'),
            },
        ),
        migrations.CreateModel(
            name='Packaging',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('code', models.CharField(max_length=50)),
                ('name', models.CharField(max_length=100)),
                ('quantity_per', models.DecimalField(blank=True, decimal_places=3, help_text='How many of the contained packaging are in one of this packaging.', max_digits=12, null=True, validators=[django.core.validators.MinValueValidator(Decimal('0.001'))])),
                ('base_unit_quantity', models.DecimalField(blank=True, decimal_places=3, help_text='Individual units in a base pack. Required only when this pack contains nothing else.', max_digits=12, null=True, validators=[django.core.validators.MinValueValidator(Decimal('0.001'))])),
                ('individual_unit_label', models.CharField(blank=True, help_text='Display label for one individual unit, for example pads.', max_length=50)),
                ('is_active', models.BooleanField(default=True)),
                ('created_at', models.DateTimeField(auto_now_add=True)),
                ('updated_at', models.DateTimeField(auto_now=True)),
                ('contains', models.ForeignKey(blank=True, help_text='Packaging this one is composed of. Empty means this is a base pack.', null=True, on_delete=django.db.models.deletion.PROTECT, related_name='contained_by', to='catalog.packaging')),
                ('factory', models.ForeignKey(on_delete=django.db.models.deletion.PROTECT, related_name='packaging', to='factories.factory')),
            ],
            options={
                'verbose_name': 'Packaging',
                'verbose_name_plural': 'Packaging',
                'ordering': ('factory', 'code'),
                'constraints': [models.UniqueConstraint(fields=('factory', 'code'), name='unique_packaging_code_per_factory'), models.CheckConstraint(condition=models.Q(models.Q(('base_unit_quantity__isnull', False), ('contains__isnull', True), ('quantity_per__isnull', True)), models.Q(('base_unit_quantity__isnull', True), ('contains__isnull', False), ('quantity_per__isnull', False)), _connector='OR'), name='packaging_base_or_composed')],
            },
        ),
        migrations.AddConstraint(
            model_name='product',
            constraint=models.UniqueConstraint(fields=('factory', 'code'), name='unique_product_code_per_factory'),
        ),
        migrations.AddConstraint(
            model_name='productvariant',
            constraint=models.UniqueConstraint(fields=('product', 'code'), name='unique_variant_code_per_product'),
        ),
    ]
